import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";
import StoreProvider from "@/components/common/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Auth-app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Layout>{children}</Layout>
        </StoreProvider>
      </body>
    </html>
  );
}
